### PR TITLE
Include related posts

### PR DESCRIPTION
**Pull request by alinebezzoco**
Hi Kiran, 

I included related posts on your blog. 
Well, I checked and you included this code correctly but you needed related posts plugin. 

Happy hacktoberfest! 

Have a nice day!

### CODE REVIEW

**Comment by kiranshahi** [comment]
Thank you @bezzocoaline for your pr

**Comment by kiranshahi** [comment]
Related post not working.

**Comment by alinebezzoco** [comment]
Hi, 
Can you send to me a print screen?

One question: Do your posts have categories or tags included? Because it's important. If not, your related post will not work.

**Comment by kiranshahi** [comment]
everythings are under this repo and its live on. http://kirans.me/blog/

**Comment by alinebezzoco** [comment]
Yep, I saw. 
But...do your posts have categories or tags included?

**Comment by kiranshahi** [comment]
Tag

**Comment by alinebezzoco** [comment]
Well, If I'm not wrong...related posts will only work if they are within post.html and not in details.html. 
I tested in my Jekyll page and it works.

**Pull request merged**
